In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Data/Titanic-Dataset.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
#percentage of missing values
missing_percent=(df.isnull().sum()/len(df))*100
print(missing_percent)

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [5]:
#fill missing values in numerical data with median
age_median=df['Age'].median()
df['Age']=df['Age'].fillna(age_median)

In [ ]:
df['Age'].isnull().sum() #numerical data use mean, median

np.int64(0)

In [8]:
df['Age'].isnull().count

<bound method Series.count of 0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool>

In [9]:
#replace category data with mode
embarked_mode=df['Embarked'].mode()[0]
df['Embarked']=df['Embarked'].fillna(embarked_mode)

In [10]:
#drop cabin column as most no. of null values
df=df.drop(columns=['Cabin'])

In [ ]:
df.isnull().sum() #to verify if there is any null value still present

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [ ]:
#DUPLICATED ROWS, to reduce redundancy, model trained on biased data
duplicate_rows=df.duplicated().sum()
print("Duplicated Rows: ",duplicate_rows) #no duplicate rows

Duplicated Rows:  0

In [ ]:
#if duplicates are present
#df=df.drop_duplicates()

In [ ]:
#Outlier box plot for age, fare
Q1=df['Fare'].quantile(0.25)
Q3=df['Fare'].quantile(0.75)
IQR=Q3-Q1
lb=Q1-1.5*IQR
ub=Q3+1.5*IQR
df=df[(df['Fare']>=lb)&(df['Fare']<=ub)] #to update df and remove all the outliers from fare column

In [14]:
#check unique values
sex_unique=df['Sex'].unique()
print(sex_unique)

<StringArray>
['male', 'female']
Length: 2, dtype: str

In [15]:
#check unique values in embarked
embarked_unique=df['Embarked'].unique()
print(embarked_unique)

<StringArray>
['S', 'Q', 'C']
Length: 3, dtype: str

In [18]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S
5         0       3    male  28.0      0      0   8.4583        Q

In [ ]:
#droping the columns that are not important, or yk just the use case
df=df.drop(columns=['PassengerId','Name','Ticket']) #if ran once then dont run again else error

In [20]:
#to strip the space in column name
df.columns.str.strip()

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked'],
      dtype='str')

In [ ]:
#feature scaling for ml model
from sklearn.preprocessing import StandardScaler

In [ ]:
df.to_csv("Data/Titanic_Cleaned.csv",index=False) #to save the cleaned dataset separately